default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: sample_app_db

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: sample_app_db

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: sample_app_db
